### ISSUE TITLE
Checklist items are not in the same order as in Trello after adjusting order in Trello

### ISSUE THREAD

**Issue by darthmachina** [OfficerHalf/obsidian-trello#31]
# Issue
I use checklists pretty extensively in Trello, and will reorder them quite a bit as I like to work top down. However, in the plugin view it looks like the checklist items are in order according to when they were added to the card.

## Trello
![image](https://user-images.githubusercontent.com/3865380/137181560-5c460384-0e6a-48f0-9a9f-2d23bd904744.png)
You can see here I moved the item I added third to the second position

## Obsidian
![image](https://user-images.githubusercontent.com/3865380/137181587-9779ddd2-b7bb-400a-96f4-a6ffba753f4d.png)
And you can see here that the order is still by when they were added

# Expected Behavior
The checklist items should be in the same order as they appear in Trello

# Versions
Obsidian: 0.12.18
Trello Plugin: 1.4.0

**Comment by OfficerHalf** [comment]
Fixed in v1.5.0.
