### ISSUE TITLE
Trello pane buttons broken after updating to Obsidian 0.15.6

### ISSUE THREAD

**Issue by warenzema** [OfficerHalf/obsidian-trello#43]
Steps to reproduce:
1. Upgrade Obsidian
2. Click [Connect Trello Card] button

Expected behavior: Something appears allowing me to find the card I want to connect to.
Actual behavior: Nothing happens. Nothing appears in console, either, as a result of clicking.

Background:
Last night I installed obsidian-trello and verified it was working fine. I successfully connected a card, sent a comment to trello, and was able to read from Trello a description I had added to said Trello card.
This morning I was playing with other plugins (I'm very new to Obsidian) and at one point restarted Obsidian as part of trouble shooting. I believe it updated to the latest version then, as the editor behavior had changed, which I traced to "Live Preview" being toggled on, which is new with this Obsidian version.
I then notice I could no longer connect cards with this plugin. (The test card I had connected last night was still connected, and I was still able to click it and have the Trello card open in my browser, as expected. No other tests were performed before I reinstalled obsidian-trello to try to figure out what was wrong.)

Suspected issue:
The [release notes](https://forum.obsidian.md/t/obsidian-release-v0-15-6/40227) have a [guide](https://forum.obsidian.md/t/plugin-developers-how-to-update-your-plugin-to-support-pop-out-windows/40228) for developers to update their plugins.

I believe the issue I am experiencing occurs on line 188 of https://github.com/OfficerHalf/obsidian-trello/blob/main/src/plugin.ts

There may be more issues (including line 294 of that file), but I have zero Obsidian plugin development experience, and less than a year of Typescript experience, and only about a week or so of using Obsidian, so this might actually be PEBKAC and I've wrote all this for nothing.

Hopefully this is useful for debugging the issue I encountered, as I gathered from other issues that this plugin may no longer be a high priority for you to work on.

**Comment by OfficerHalf** [comment]
Wow, excellent investigation, links, and context! This is an S tier issue, @warenzema. 😄 I'll look into it. While feature work on this plugin isn't the highest priority for me, this still deserves fixing.

**Comment by OfficerHalf** [comment]
@warenzema after a bit of investigation, it seems just that one button is broken thankfully; you can still link cards using the command palette for now:
Cmd/Ctrl + P > Obsidian Trello: Connect Trello card

**Comment by OfficerHalf** [comment]
@warenzema should be fixed in v1.6.1
