### ISSUE TITLE
How to configure the Trello API?

### ISSUE THREAD

**Issue by wenlzhang** [OfficerHalf/obsidian-trello#46]
I generated a Personal Key in the Developer API Keys section of my Trello account. However, I did not know how to configure the Allowed Origins part.

Maybe because of this, I get the following error in Obsidian when trying to access my Trello cards:

`Failed to load resource: the server responded with a status of 401 ()`

I am using Obsidian version 0.16.2 and Obsidian Trello version 1.6.1.

**Comment by OfficerHalf** [comment]
This should be fixed now #51
