### ISSUE TITLE
Hide Trello card ID

### ISSUE THREAD

**Issue by slim71** [OfficerHalf/obsidian-trello#49]
I've noticed that when I attach a Trello card to a note, at the top of said note lies some kind of header like `trello_plugin_note_id: XXXX`.
Is there any way to hide this from the note itself, _in reading mode_? I'd prefer to only look at the Trello card from the dedicated side panel...
![image](https://user-images.githubusercontent.com/39267642/224574968-61dd9c22-d10e-4cfa-a6c6-1f36c045430a.png)

**Comment by OfficerHalf** [comment]
I don't think the YAML frontmatter is displayed in read mode. Do you have a plugin that displays it, or perhaps it's your theme?

**Comment by slim71** [comment]
mmmm
I'll have to check that, I'm not sure... Thanks!

**Comment by slim71** [comment]
I can't seem to find the source, unfortunately...
Just to be sure, I'd like to add this: as soon as I link a card, the appearance is like this
![image](https://user-images.githubusercontent.com/39267642/224577387-162f7236-dce0-4d24-a71b-38134855ee66.png)
but if I open another note and come back to this one, it seems the ID displayed is just copied over
![image](https://user-images.githubusercontent.com/39267642/224577420-e5bd8ff6-487b-4554-a1b1-668b0d3b5e87.png)

It must be some other plugin or theme setting, but unfortunately I can't seem to find it for now. I'll just delete the extra bit, thanks!

**Comment by OfficerHalf** [comment]
Can you reliably reproduce that duplication? It shouldn't add another YAML block. That's definitely why it's visible; the way I modify the metadata is probably out of date, but I've not been updating this plugin since I don't even use Trello anymore.

**Comment by slim71** [comment]
Seems like I can.

Upon opening Obsidian, if I link a card to a note this happens. Navigating to and back from another note, the correct YAML is shown but there's also the extra bit.
Deleting everything and re-linking seems to create the correct YAML, with no extra bit. From this point on, it seems even linking another note to a card does not create the extra bit.

I'm open to provide videos or logs or whatever if needed!
